name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the form below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I try to..., the following happens...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Initialize client with '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages if applicable.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Python SDK
        - TypeScript SDK
        - Go SDK
        - CLI
        - Web UI
        - API Server
        - Worker
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: e.g., 0.1.0, latest, commit sha
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      description: How are you running AgentTrace?
      options:
        - Self-hosted (Docker Compose)
        - Self-hosted (Kubernetes)
        - Cloud
        - Local development
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide relevant environment details:
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Python/Node/Go version (if using SDK)
        - Browser (if UI issue)
      placeholder: |
        - OS: macOS 14.0
        - Python: 3.11.5
        - Browser: Chrome 120
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for existing issues that describe my problem
          required: true
        - label: I have read the [troubleshooting guide](https://docs.agenttrace.io/troubleshooting)
          required: false
