name: Question
description: Ask a question about AgentTrace
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about AgentTrace? We're here to help!

        Before asking, please check:
        - [Documentation](https://docs.agenttrace.io)
        - [Troubleshooting Guide](https://docs.agenttrace.io/troubleshooting)
        - [Existing Issues](https://github.com/agenttrace/agenttrace/issues?q=is%3Aissue)

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...? / What is the best way to...? / Is it possible to...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What is your question about?
      options:
        - Getting Started / Setup
        - SDK Usage (Python/TypeScript/Go)
        - API Usage
        - Tracing & Observations
        - Prompt Management
        - Evaluations & Scores
        - Datasets & Experiments
        - Agent Features (Checkpoints, Git, etc.)
        - Self-Hosting / Deployment
        - Integrations
        - Performance / Scaling
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Provide any relevant context that might help us answer your question.
        - What are you trying to accomplish?
        - What have you tried so far?
        - Any relevant code snippets?
      placeholder: |
        I'm trying to...

        Here's what I've tried:
        ```python
        # code
        ```
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Include version info if your question is related to a specific setup.
      placeholder: |
        - AgentTrace version: 0.1.0
        - SDK: Python 0.1.0
        - Python version: 3.11
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched the documentation
          required: true
        - label: I have searched existing issues
          required: true
