#!/bin/bash

echo "=== AgentTrace Dev Container Started ==="
echo ""
echo "Services available:"
echo "  - PostgreSQL:     localhost:5432"
echo "  - ClickHouse:     localhost:9000 (native), localhost:8123 (HTTP)"
echo ""
echo "Optional full-stack services are disabled by default."
echo "From the host repository, start them with:"
echo "  docker compose --project-name agenttrace-devcontainer -f .devcontainer/docker-compose.yml --profile full up -d redis minio"
echo ""
echo "Quick commands:"
echo "  Start API:        cd /workspace/api && make run-core"
echo "  Start Web:        cd /workspace/web && npm run dev"
echo "  Run API tests:    cd /workspace/api && make test"
echo "  Run Web tests:    cd /workspace/web && npm test"
echo ""
