package domain

import (
	"time"

	"github.com/google/uuid"
)

// FailureCategory represents the category of a failure
type FailureCategory string

const (
	FailureCategoryPrompt         FailureCategory = "prompt_issue"
	FailureCategoryModel          FailureCategory = "model_limitation"
	FailureCategoryContext         FailureCategory = "context_overflow"
	FailureCategoryTool           FailureCategory = "tool_failure"
	FailureCategoryData           FailureCategory = "data_quality"
	FailureCategoryTimeout        FailureCategory = "timeout"
	FailureCategoryRateLimit      FailureCategory = "rate_limit"
	FailureCategoryInfrastructure FailureCategory = "infrastructure"
)

// RCAReport represents a root cause analysis report
type RCAReport struct {
	ID                  uuid.UUID            `json:"id"`
	ProjectID           uuid.UUID            `json:"projectId"`
	TraceID             uuid.UUID            `json:"traceId"`
	PrimaryCategory     FailureCategory      `json:"primaryCategory"`
	Confidence          float64              `json:"confidence"`
	Summary             string               `json:"summary"`
	DetailedAnalysis    string               `json:"detailedAnalysis"`
	ContributingFactors []ContributingFactor `json:"contributingFactors"`
	Remediations        []Remediation        `json:"remediations"`
	SimilarIncidents    []uuid.UUID          `json:"similarIncidents,omitempty"`
	AnalyzedAt          time.Time            `json:"analyzedAt"`
}

// ContributingFactor represents a factor that contributed to a failure
type ContributingFactor struct {
	Category    FailureCategory `json:"category"`
	Description string          `json:"description"`
	Evidence    string          `json:"evidence"`
	Impact      float64         `json:"impact"` // 0-1
}

// Remediation represents a recommended action to fix a failure
type Remediation struct {
	Priority    int    `json:"priority"` // 1=highest
	Action      string `json:"action"`
	Description string `json:"description"`
	Automated   bool   `json:"automated"`
}

// RCAInput represents the input for triggering root cause analysis
type RCAInput struct {
	TraceID uuid.UUID `json:"traceId" validate:"required"`
}

// CorrelatedAnomaly represents anomalies correlated across traces
type CorrelatedAnomaly struct {
	ID             uuid.UUID              `json:"id"`
	ProjectID      uuid.UUID              `json:"projectId"`
	AnomalyType    string                 `json:"anomalyType"` // latency_spike, error_burst, cost_surge, quality_drop, model_degradation, prompt_drift
	Severity       string                 `json:"severity"`    // info, warning, critical, emergency
	Title          string                 `json:"title"`
	Description    string                 `json:"description"`
	AffectedTraces []string               `json:"affectedTraces"`
	AffectedModels []string               `json:"affectedModels,omitempty"`
	Correlation    float64                `json:"correlation"` // 0-1 confidence
	RootCauses     []ContributingFactor   `json:"rootCauses"`
	Remediations   []Remediation          `json:"remediations"`
	Status         string                 `json:"status"` // open, acknowledged, investigating, resolved, dismissed
	AssignedTo     *uuid.UUID             `json:"assignedTo,omitempty"`
	DetectedAt     time.Time              `json:"detectedAt"`
	ResolvedAt     *time.Time             `json:"resolvedAt,omitempty"`
	Metadata       map[string]interface{} `json:"metadata,omitempty"`
}

// IntelligentAlert represents an alert generated by the correlation engine
type IntelligentAlert struct {
	ID             uuid.UUID  `json:"id"`
	ProjectID      uuid.UUID  `json:"projectId"`
	AnomalyID      uuid.UUID  `json:"anomalyId"`
	AlertRuleID    *uuid.UUID `json:"alertRuleId,omitempty"`
	Channel        string     `json:"channel"` // slack, pagerduty, opsgenie, email, webhook
	Title          string     `json:"title"`
	Message        string     `json:"message"`
	Severity       string     `json:"severity"`
	Status         string     `json:"status"`         // pending, sent, acknowledged, resolved, failed
	DeliveryStatus string     `json:"deliveryStatus"` // queued, delivered, failed
	SentAt         *time.Time `json:"sentAt,omitempty"`
	AcknowledgedAt *time.Time `json:"acknowledgedAt,omitempty"`
	AcknowledgedBy *uuid.UUID `json:"acknowledgedBy,omitempty"`
	CreatedAt      time.Time  `json:"createdAt"`
}

// AlertDeliveryChannel configures alert delivery
type AlertDeliveryChannel struct {
	ID         uuid.UUID         `json:"id"`
	ProjectID  uuid.UUID         `json:"projectId"`
	Name       string            `json:"name"`
	Type       string            `json:"type"` // slack, pagerduty, opsgenie, email, webhook
	Config     map[string]string `json:"config"`
	Enabled    bool              `json:"enabled"`
	TestStatus string            `json:"testStatus,omitempty"` // untested, success, failed
	CreatedAt  time.Time         `json:"createdAt"`
}

// CorrelationRule defines how anomalies are correlated
type CorrelationRule struct {
	ID             uuid.UUID `json:"id"`
	ProjectID      uuid.UUID `json:"projectId"`
	Name           string    `json:"name"`
	AnomalyTypes   []string  `json:"anomalyTypes"`   // which anomaly types to correlate
	WindowMinutes  int       `json:"windowMinutes"`   // correlation time window
	MinCorrelation float64   `json:"minCorrelation"`  // minimum correlation threshold
	AutoRemediate  bool      `json:"autoRemediate"`
	Severity       string    `json:"severity"`
	Channels       []string  `json:"channels"` // delivery channel IDs
	Enabled        bool      `json:"enabled"`
	CreatedAt      time.Time `json:"createdAt"`
}

// RCAInvestigation represents an ongoing investigation
type RCAInvestigation struct {
	ID             uuid.UUID              `json:"id"`
	ProjectID      uuid.UUID              `json:"projectId"`
	AnomalyID      uuid.UUID              `json:"anomalyId"`
	Title          string                 `json:"title"`
	Status         string                 `json:"status"` // open, investigating, root_cause_found, resolved
	Findings       []InvestigationFinding `json:"findings"`
	Timeline       []InvestigationEvent   `json:"timeline"`
	RootCause      string                 `json:"rootCause,omitempty"`
	Resolution     string                 `json:"resolution,omitempty"`
	InvestigatorID uuid.UUID              `json:"investigatorId"`
	CreatedAt      time.Time              `json:"createdAt"`
	UpdatedAt      time.Time              `json:"updatedAt"`
}

// InvestigationFinding represents a finding during investigation
type InvestigationFinding struct {
	Type        string  `json:"type"` // observation, hypothesis, evidence, conclusion
	Description string  `json:"description"`
	Confidence  float64 `json:"confidence"`
	TraceID     string  `json:"traceId,omitempty"`
	SpanID      string  `json:"spanId,omitempty"`
}

// InvestigationEvent represents a timeline event in an investigation
type InvestigationEvent struct {
	Action    string    `json:"action"`
	Details   string    `json:"details"`
	UserID    uuid.UUID `json:"userId"`
	Timestamp time.Time `json:"timestamp"`
}

// AlertDashboardStats provides alerting overview statistics
type AlertDashboardStats struct {
	OpenAnomalies        int     `json:"openAnomalies"`
	CriticalAlerts       int     `json:"criticalAlerts"`
	ActiveInvestigations int     `json:"activeInvestigations"`
	MTTR                 float64 `json:"mttrMinutes"` // mean time to resolve
	AlertsSentToday      int     `json:"alertsSentToday"`
	AnomalyTrend         string  `json:"anomalyTrend"` // increasing, stable, decreasing
}

// CorrelatedAnomalyInput represents input for creating a correlated anomaly
type CorrelatedAnomalyInput struct {
	AnomalyType    string   `json:"anomalyType" validate:"required"`
	Title          string   `json:"title" validate:"required"`
	Description    string   `json:"description,omitempty"`
	AffectedTraces []string `json:"affectedTraces,omitempty"`
	Severity       string   `json:"severity,omitempty"`
}

// DeliveryChannelInput represents input for creating an alert delivery channel
type DeliveryChannelInput struct {
	Name   string            `json:"name" validate:"required"`
	Type   string            `json:"type" validate:"required"`
	Config map[string]string `json:"config" validate:"required"`
}

// CorrelationRuleInput represents input for creating a correlation rule
type CorrelationRuleInput struct {
	Name           string   `json:"name" validate:"required"`
	AnomalyTypes   []string `json:"anomalyTypes" validate:"required"`
	WindowMinutes  int      `json:"windowMinutes,omitempty"`
	MinCorrelation float64  `json:"minCorrelation,omitempty"`
	Severity       string   `json:"severity,omitempty"`
	Channels       []string `json:"channels,omitempty"`
	AutoRemediate  bool     `json:"autoRemediate,omitempty"`
}
