// Code generated by gqlgen, DO NOT EDIT.

package api

import (
	"fmt"
	"io"
	"strconv"
)

// AnnotationStatus represents the status of an annotation queue item
type AnnotationStatus string

const (
	AnnotationStatusPending    AnnotationStatus = "PENDING"
	AnnotationStatusInProgress AnnotationStatus = "IN_PROGRESS"
	AnnotationStatusCompleted  AnnotationStatus = "COMPLETED"
)

var AllAnnotationStatus = []AnnotationStatus{
	AnnotationStatusPending,
	AnnotationStatusInProgress,
	AnnotationStatusCompleted,
}

func (e AnnotationStatus) IsValid() bool {
	switch e {
	case AnnotationStatusPending, AnnotationStatusInProgress, AnnotationStatusCompleted:
		return true
	}
	return false
}

func (e AnnotationStatus) String() string {
	return string(e)
}

func (e *AnnotationStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnnotationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnnotationStatus", str)
	}
	return nil
}

func (e AnnotationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

// PromptMessage represents a message in a prompt
type PromptMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}
